-- 1
SELECT * FROM DARBUOTOJAI;

-- 2
SELECT GIMIMO_DATA FROM DARBUOTOJAI;

-- 3
SELECT VARDAS, PAVARDĖ, PAREIGOS FROM DARBUOTOJAI;

-- 4
SELECT DISTINCT SKYRIUS_PAVADINIMAS FROM DARBUOTOJAI;

-- 5
SELECT * FROM DARBUOTOJAI WHERE SKYRIUS_PAVADINIMAS = "Gamybos";

-- 6
SELECT PAREIGOS FROM DARBUOTOJAI WHERE VARDAS = "Giedrius";

-- 7
SELECT * FROM DARBUOTOJAI WHERE GIMIMO_DATA = "1986-09-19";

-- 8
SELECT VARDAS FROM DARBUOTOJAI WHERE PAVARDĖ = "Sabutis";

-- 9
SELECT VARDAS, PAVARDĖ FROM DARBUOTOJAI WHERE SKYRIUS_PAVADINIMAS = "Gamybos";

-- 10
INSERT INTO DARBUOTOJAI
VALUES ("Vardenis", "Pavardenis", "2023-01-17", "Tinginys", "Slunkių");

-- 11
INSERT INTO DARBUOTOJAI (VARDAS, PAVARDĖ, GIMIMO_DATA)
VALUES ("Jonas", "Petraitis", "1999-01-01");

-- 12
UPDATE DARBUOTOJAI SET PAREIGOS = "Tinginys", SKYRIUS_PAVADINIMAS = "Slunkių"
WHERE PAVARDĖ = "Petraitis";

-- 13
DELETE FROM DARBUOTOJAI WHERE GIMIMO_DATA = "1999-01-01";

-- 14
INSERT INTO DARBUOTOJAI (PAVARDĖ, PAREIGOS)
VALUES ("Antanaitis", "Programuotojas"), ("Antanaitis", "Programuotojas");

-- 15
UPDATE DARBUOTOJAI SET PAREIGOS = "Testuotojas" WHERE PAVARDĖ = "Antanaitis";

-- 16
SELECT COUNT("Testuotojas")
FROM DARBUOTOJAI WHERE PAREIGOS = "Testuotojas";

--

SELECT * FROM DARBUOTOJAI ORDER BY PAREIGOS;