-- 1
SELECT VARDAS, PAVARDĖ, PROJEKTAS.PAVADINIMAS FROM DARBUOTOJAS
    JOIN PROJEKTAS ON PROJEKTAS_ID = PROJEKTAS.ID;

-- 2
SELECT VARDAS, PAVARDĖ, PROJEKTAS.PAVADINIMAS FROM DARBUOTOJAS
    JOIN PROJEKTAS ON PROJEKTAS_ID = PROJEKTAS.ID
    WHERE PROJEKTAS.PAVADINIMAS = "Galerija";

-- 3
SELECT VARDAS, PAVARDĖ FROM DARBUOTOJAS
    JOIN PROJEKTAS ON PROJEKTAS_ID = PROJEKTAS.ID
    JOIN SKYRIUS ON SKYRIUS_ID = SKYRIUS.ID
    WHERE PROJEKTAS.PAVADINIMAS = "Projektų valdymas" AND SKYRIUS.ID = 3;

-- 4
SELECT VARDAS, PAVARDĖ, PROJEKTAS.PAVADINIMAS FROM DARBUOTOJAS
    JOIN PROJEKTAS ON PROJEKTAS_ID = PROJEKTAS.ID
    WHERE PROJEKTAS.PAVADINIMAS = "Projektų valdymas" AND ASMENS_KODAS LIKE ("4%");

-- 5
SELECT PAVADINIMAS, count(*) as count FROM SKYRIUS
    JOIN DARBUOTOJAS ON SKYRIUS_ID = SKYRIUS.ID
    GROUP BY PAVADINIMAS;

-- 6
SELECT PAVADINIMAS, count(*) as count FROM SKYRIUS
    JOIN DARBUOTOJAS ON SKYRIUS_ID = SKYRIUS.ID
    GROUP BY PAVADINIMAS
    HAVING count >= 5;

-- 7
SELECT VARDAS, PAVARDĖ, PAREIGOS, SKYRIUS.PAVADINIMAS FROM DARBUOTOJAS
    JOIN SKYRIUS ON SKYRIUS_ID = SKYRIUS.ID
    WHERE NOT PAREIGOS = "Vadovas";

-- 8
INSERT INTO DARBUOTOJAS (ASMENS_KODAS, VARDAS, PAVARDĖ, DIRBA_NUO)
    VALUES ("38807117896", "Pranas", "Logis", "2009-11-12");

-- 9
SELECT VARDAS, PAVARDĖ, SKYRIUS.PAVADINIMAS FROM DARBUOTOJAS
    LEFT JOIN SKYRIUS ON SKYRIUS_ID = SKYRIUS.ID;

-- 10
SELECT VARDAS, PAVARDĖ, PAVADINIMAS FROM DARBUOTOJAS
    JOIN PROJEKTAS ON PROJEKTAS_ID = PROJEKTAS.ID
    WHERE PAVADINIMAS IN (
        SELECT PAVADINIMAS FROM PROJEKTAS
            JOIN DARBUOTOJAS ON PROJEKTAS_ID = PROJEKTAS.ID
            GROUP BY PAVADINIMAS
            HAVING count(*) > 4
    );

-- 11
SELECT VARDAS, PAVARDĖ, (BAZINIS_ATLYGINIMAS + PRIEDAI) AS BENDRAS_ATLYGINIMAS FROM DARBUOTOJAS;

-- 12
SELECT SUM(BAZINIS_ATLYGINIMAS + PRIEDAI) AS atlyginimu_ir_priedu_suma, ROUND(AVG(BAZINIS_ATLYGINIMAS), 2) as vidutinis_atlyginimas, MAX(BAZINIS_ATLYGINIMAS) as didziausias_atlyginimas, MIN(BAZINIS_ATLYGINIMAS) as maziausias_atlyginimas FROM DARBUOTOJAS;



SELECT * FROM DARBUOTOJAS;

SELECT * FROM PROJEKTAS;

SELECT * FROM SKYRIUS;